# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='doc',
            field=models.FileField(default=b'doc/none/no-pdf.doc', upload_to=b'doc/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='doc',
            field=models.FileField(default=b'doc/none/no-pdf.doc', upload_to=b'doc/'),
        ),
    ]
